<x-layouts.app title="Verkoopfacturen" :$domainUser :$administrationContext :$canViewRelations :$canViewSales>
    <div class="flex flex-wrap items-center justify-between gap-4">
        <div><h1 class="text-2xl font-bold">Facturen</h1><p class="mt-1 text-slate-600">Bekijk en beheer directe verkoopfacturen.</p></div>
        @if($canManageInvoiceDrafts)<a href="{{ route('sales.invoices.create') }}" class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-blue-700">Nieuwe factuur</a>@endif
    </div>
    <form method="GET" action="{{ route('sales.invoices.index') }}" class="mt-6 grid gap-4 rounded-xl bg-white p-4 shadow-sm md:grid-cols-4">
        <label class="md:col-span-2">Zoeken<input name="q" value="{{ request('q') }}" class="mt-1 w-full rounded-lg border-slate-300" placeholder="Factuurnummer of klant"></label>
        <label>Status<select name="status" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Alle statussen</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $statusPresenter::label($status) }}</option>@endforeach</select></label>
        <label>Klant<select name="customer" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Alle klanten</option>@foreach($customers as $customer)<option value="{{ $customer['id'] }}" @selected(request('customer')===$customer['id'])>{{ $customer['number'] }} · {{ $customer['name'] }}</option>@endforeach</select></label>
        <label>Vanaf<input type="date" name="date_from" value="{{ request('date_from') }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
        <label>Tot en met<input type="date" name="date_to" value="{{ request('date_to') }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
        <label>Sorteren<select name="sort" class="mt-1 w-full rounded-lg border-slate-300">@foreach(['invoice_date'=>'Factuurdatum','due_date'=>'Vervaldatum','number'=>'Factuurnummer','customer_name'=>'Klant','status'=>'Status'] as $value=>$label)<option value="{{ $value }}" @selected(request('sort','invoice_date')===$value)>{{ $label }}</option>@endforeach</select></label>
        <label>Richting<select name="direction" class="mt-1 w-full rounded-lg border-slate-300"><option value="desc" @selected(request('direction','desc')==='desc')>Aflopend</option><option value="asc" @selected(request('direction')==='asc')>Oplopend</option></select></label>
        <div class="flex items-end gap-3"><button class="rounded-lg bg-slate-900 px-4 py-3 font-semibold text-white">Filteren</button>@if($hasActiveFilters)<a href="{{ route('sales.invoices.index') }}" class="px-3 py-3 font-semibold text-blue-700">Wissen</a>@endif</div>
    </form>
    @if($invoices->total()===0)
        <div class="mt-6 rounded-xl bg-white p-8 text-center shadow-sm"><p>{{ $hasActiveFilters ? 'Geen verkoopfacturen gevonden met deze filters.' : 'Nog geen verkoopfacturen.' }}</p></div>
    @else
        <div class="mt-6 hidden overflow-x-auto rounded-xl bg-white shadow-sm md:block"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr>@foreach(['Factuurnummer','Klant','Factuurdatum','Vervaldatum','Status','Valuta','Netto','Btw','Bruto'] as $heading)<th scope="col" class="px-4 py-3">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y">@foreach($invoices->items() as $item)<tr><td class="px-4 py-3"><a class="font-semibold text-blue-700" href="{{ route('sales.invoices.show',$item->id()->toString()) }}">{{ $item->number()->value() }}</a></td><td class="px-4 py-3">{{ $item->customerName()->toString() }}</td><td class="px-4 py-3">{{ $item->invoiceDate()->format('d-m-Y') }}</td><td class="px-4 py-3">{{ $item->dueDate()->format('d-m-Y') }}</td><td class="px-4 py-3">{{ $statusPresenter::label($item->status()) }}</td><td class="px-4 py-3">{{ $item->currency()->code() }}</td><td class="px-4 py-3">{{ $moneyFormatter->format($item->netTotal()) }}</td><td class="px-4 py-3">{{ $moneyFormatter->format($item->taxTotal()) }}</td><td class="px-4 py-3 font-semibold">{{ $moneyFormatter->format($item->grossTotal()) }}</td></tr>@endforeach</tbody></table></div>
        <div class="mt-6 space-y-3 md:hidden">@foreach($invoices->items() as $item)<a href="{{ route('sales.invoices.show',$item->id()->toString()) }}" class="block rounded-xl bg-white p-4 shadow-sm"><span class="font-bold text-blue-700">{{ $item->number()->value() }}</span><span class="float-right">{{ $statusPresenter::label($item->status()) }}</span><p class="mt-2">{{ $item->customerName()->toString() }}</p><p class="text-sm text-slate-600">{{ $item->invoiceDate()->format('d-m-Y') }} · vervalt {{ $item->dueDate()->format('d-m-Y') }}</p><dl class="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt class="text-slate-500">Netto</dt><dd>{{ $moneyFormatter->format($item->netTotal()) }}</dd></div><div><dt class="text-slate-500">Btw</dt><dd>{{ $moneyFormatter->format($item->taxTotal()) }}</dd></div><div><dt class="text-slate-500">Totaal</dt><dd class="font-semibold">{{ $moneyFormatter->format($item->grossTotal()) }}</dd></div></dl></a>@endforeach</div>
        @php($lastPage=max(1,(int)ceil($invoices->total()/$invoices->perPage())))
        <nav class="mt-6 flex justify-between" aria-label="Paginering">@if($invoices->page()>1)<a class="font-semibold text-blue-700" href="{{ route('sales.invoices.index',$queryParameters+['page'=>$invoices->page()-1]) }}">Vorige</a>@else<span></span>@endif<span>Pagina {{ $invoices->page() }} van {{ $lastPage }}</span>@if($invoices->page()<$lastPage)<a class="font-semibold text-blue-700" href="{{ route('sales.invoices.index',$queryParameters+['page'=>$invoices->page()+1]) }}">Volgende</a>@endif</nav>
    @endif
</x-layouts.app>
