<x-layouts.app title="Verkoopfactuur {{ $invoice->number()->value() }}" :$domainUser :$administrationContext :$canViewRelations :$canViewSales>
    <div class="flex flex-wrap items-start justify-between gap-4">
        <div><p class="text-sm font-medium text-slate-500">Verkoopfactuur</p><h1 class="text-2xl font-bold">{{ $invoice->number()->value() }}</h1><p class="mt-1">{{ $statusPresenter::label($invoice->status()) }}</p></div>
        @if($canManageInvoiceDrafts && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Draft)<a href="{{ route('sales.invoices.edit',$invoice->id()->toString()) }}" class="rounded-lg border border-blue-700 px-4 py-3 font-semibold text-blue-700">Header bewerken</a>@endif
    </div>
    <section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Factuurgegevens</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-sm text-slate-500">Klantnummer</dt><dd class="font-semibold">{{ $invoice->customer()->customerNumber()->toString() }}</dd></div><div><dt class="text-sm text-slate-500">Klant</dt><dd class="font-semibold">{{ $invoice->customer()->displayName()->toString() }}</dd></div><div><dt class="text-sm text-slate-500">Factuurdatum</dt><dd>{{ $invoice->invoiceDate()->format('d-m-Y') }}</dd></div><div><dt class="text-sm text-slate-500">Vervaldatum</dt><dd>{{ $invoice->dueDate()->format('d-m-Y') }}</dd></div><div><dt class="text-sm text-slate-500">Valuta</dt><dd>{{ $invoice->currency()->code() }}</dd></div><div><dt class="text-sm text-slate-500">Bronorder</dt><dd>@if($invoice->sourceOrderId())<a class="text-blue-700" href="{{ route('sales.orders.show',$invoice->sourceOrderId()->toString()) }}">Bekijk order</a>@else Geen (directe factuur) @endif</dd></div></dl></section>
    <section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Factuuradres</h2><address class="mt-3 not-italic">{{ $invoice->invoiceAddress()->addressLine()->value() }}<br>@if($invoice->invoiceAddress()->addressLine2()){{ $invoice->invoiceAddress()->addressLine2()->value() }}<br>@endif{{ $invoice->invoiceAddress()->postalCode()->value() }} {{ $invoice->invoiceAddress()->city()->value() }}<br>{{ $invoice->invoiceAddress()->countryCode()->value() }}</address></section>
    <section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Factuurregels</h2>
        @if($invoice->lines()===[])<p class="mt-3 text-slate-600">Nog geen factuurregels.</p>@else
            <div class="mt-4 hidden overflow-x-auto md:block"><table class="w-full text-left text-sm"><thead><tr>@foreach(['Omschrijving','Aantal','Prijs per eenheid','Btw-code','Btw-tarief','Netto'] as $heading)<th scope="col" class="px-3 py-2">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y">@foreach($invoice->lines() as $line)<tr><td class="px-3 py-3">{{ $line->description()->value() }}</td><td class="px-3 py-3">{{ $line->quantity()->value() }}</td><td class="px-3 py-3">{{ $moneyFormatter->format($line->unitPrice()) }}</td><td class="px-3 py-3">{{ $line->taxSnapshot()?->taxCode()->value() }} · {{ $line->taxSnapshot()?->taxCodeName()->value() }}</td><td class="px-3 py-3">{{ $line->taxSnapshot()?->taxRate()->value() }}%</td><td class="px-3 py-3">{{ $moneyFormatter->format($line->lineTotal()) }}</td></tr>@endforeach</tbody></table></div>
            <div class="mt-4 space-y-3 md:hidden">@foreach($invoice->lines() as $line)<article class="rounded-lg border p-4"><h3 class="font-semibold">{{ $line->description()->value() }}</h3><p class="mt-2 text-sm">{{ $line->quantity()->value() }} × {{ $moneyFormatter->format($line->unitPrice()) }}</p><p class="text-sm">{{ $line->taxSnapshot()?->taxCode()->value() }} · {{ $line->taxSnapshot()?->taxRate()->value() }}%</p><p class="mt-2 font-semibold">Netto {{ $moneyFormatter->format($line->lineTotal()) }}</p></article>@endforeach</div>
        @endif
        @if($canManageInvoiceDrafts && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Draft && $invoice->sourceOrderId() === null)
            @if($taxCodes===[])<div class="mt-5 rounded-lg bg-amber-50 p-4 text-amber-900" role="status"><strong>Geen btw-codes beschikbaar.</strong> Configureer eerst een actieve verkoop-btw-code voordat je factuurregels toevoegt of wijzigt.</div>@else
                @foreach($invoice->lines() as $line)<details class="mt-4 rounded-lg border p-4"><summary class="cursor-pointer font-semibold text-blue-700">Regel bewerken: {{ $line->description()->value() }}</summary><form method="POST" action="{{ route('sales.invoices.lines.update',[$invoice->id()->toString(),$line->id()->toString()]) }}" class="mt-3 grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<label>Omschrijving<input name="description" required value="{{ $line->description()->value() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Aantal<input name="quantity" inputmode="decimal" required value="{{ $line->quantity()->value() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Prijs per eenheid<input name="unit_price" inputmode="decimal" required value="{{ $line->unitPrice()->amount() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Btw-code<select name="tax_code_id" required class="mt-1 w-full rounded-lg border-slate-300">@foreach($taxCodes as $taxCode)<option value="{{ $taxCode->id()->toString() }}" @selected($line->taxSnapshot()?->taxCodeId()->equals($taxCode->id()))>{{ $taxCode->code()->value() }} · {{ $taxCode->name()->value() }} · {{ $taxCode->rate()->value() }}%</option>@endforeach</select></label><button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white sm:col-span-2">Regel opslaan</button></form><form method="POST" action="{{ route('sales.invoices.lines.destroy',[$invoice->id()->toString(),$line->id()->toString()]) }}" class="mt-3">@csrf @method('DELETE')<button class="rounded-lg border border-red-700 px-4 py-3 font-semibold text-red-700">Regel verwijderen</button></form></details>@endforeach
                <section class="mt-6 border-t pt-5"><h3 class="font-bold">Regel toevoegen</h3><form method="POST" action="{{ route('sales.invoices.lines.store',$invoice->id()->toString()) }}" class="mt-4 grid gap-4 sm:grid-cols-2">@csrf<label>Omschrijving<input name="description" required value="{{ old('description') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('description')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Aantal<input name="quantity" inputmode="decimal" required value="{{ old('quantity') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('quantity')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Prijs per eenheid<input name="unit_price" inputmode="decimal" required value="{{ old('unit_price') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('unit_price')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Btw-code<select name="tax_code_id" required class="mt-1 w-full rounded-lg border-slate-300"><option value="">Selecteer een btw-code</option>@foreach($taxCodes as $taxCode)<option value="{{ $taxCode->id()->toString() }}" @selected(old('tax_code_id')===$taxCode->id()->toString())>{{ $taxCode->code()->value() }} · {{ $taxCode->name()->value() }} · {{ $taxCode->rate()->value() }}%</option>@endforeach</select>@error('tax_code_id')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white sm:col-span-2">Regel toevoegen</button></form></section>
            @endif
        @endif
    </section>
    <section class="mt-6 rounded-xl bg-slate-900 p-6 text-white"><h2 class="text-lg font-bold">Totalen</h2><dl class="mt-4 ml-auto grid max-w-md gap-3"><div class="flex justify-between"><dt>Netto</dt><dd>{{ $moneyFormatter->format($invoice->netTotal()) }}</dd></div><div class="flex justify-between"><dt>Btw</dt><dd>{{ $moneyFormatter->format($invoice->taxTotal()) }}</dd></div><div class="flex justify-between border-t border-slate-600 pt-3 text-lg font-bold"><dt>Totaal</dt><dd>{{ $moneyFormatter->format($invoice->grossTotal()) }}</dd></div></dl></section>
    @if(($canIssueInvoices && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Draft) || ($canManageInvoiceDrafts && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Draft) || ($canIssueInvoices && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Finalized) || ($canPostInvoices && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Finalized))
        <section class="mt-6"><h2 class="text-lg font-bold">Acties</h2><div class="mt-3 flex flex-wrap gap-3">@if($canIssueInvoices && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Draft)<form method="POST" action="{{ route('sales.invoices.finalize',$invoice->id()->toString()) }}">@csrf<button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-blue-700">Factuur definitief maken</button></form>@endif @if($canPostInvoices && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Finalized)<form method="POST" action="{{ route('sales.invoices.post',$invoice->id()->toString()) }}">@csrf<button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-blue-700">Factuur boeken</button></form>@endif @if(($canManageInvoiceDrafts && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Draft) || ($canIssueInvoices && $invoice->status() === \App\Domain\Sales\Enums\SalesInvoiceStatus::Finalized))<form method="POST" action="{{ route('sales.invoices.cancel',$invoice->id()->toString()) }}">@csrf<button class="rounded-lg border border-red-700 px-4 py-3 font-semibold text-red-700 focus:ring-2 focus:ring-red-700">Factuur annuleren</button></form>@endif</div></section>
    @endif
</x-layouts.app>
