<x-layouts.app :$domainUser :$administrationContext :$canViewRelations :$canViewSales title="Offertes">
    <div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-2xl font-bold">Offertes</h1><p class="mt-1 text-slate-600">Zoek en beheer verkoopoffertes.</p></div>@if($canManageQuotations)<a href="{{ route('sales.quotations.create') }}" class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-blue-700">Nieuwe offerte</a>@endif</div>
    <form method="GET" class="mt-6 grid gap-4 rounded-xl bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-4">
        <label class="text-sm font-medium">Zoeken<input name="q" value="{{ $query->search() }}" class="mt-1 w-full rounded-lg border-slate-300" placeholder="Nummer of klant"></label>
        <label class="text-sm font-medium">Status<select name="status" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Alle statussen</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($query->status() === $status)>{{ $statusPresenter::label($status) }}</option>@endforeach</select></label>
        <label class="text-sm font-medium">Klant<select name="customer" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Alle klanten</option>@foreach($customers as $customer)<option value="{{ $customer['id'] }}" @selected($query->customerId()?->toString() === $customer['id'])>{{ $customer['number'] }} – {{ $customer['name'] }}</option>@endforeach</select></label>
        <label class="text-sm font-medium">Vanaf<input type="date" name="date_from" value="{{ $query->dateFrom()?->format('Y-m-d') }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
        <label class="text-sm font-medium">Tot<input type="date" name="date_to" value="{{ $query->dateTo()?->format('Y-m-d') }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
        <label class="text-sm font-medium">Sorteren<select name="sort" class="mt-1 w-full rounded-lg border-slate-300">@foreach(['number'=>'Offertenummer','customer_name'=>'Klant','quotation_date'=>'Offertedatum','expiry_date'=>'Vervaldatum','status'=>'Status'] as $value=>$label)<option value="{{ $value }}" @selected(request('sort','quotation_date') === $value)>{{ $label }}</option>@endforeach</select></label>
        <label class="text-sm font-medium">Richting<select name="direction" class="mt-1 w-full rounded-lg border-slate-300"><option value="desc" @selected(request('direction','desc') === 'desc')>Aflopend</option><option value="asc" @selected(request('direction') === 'asc')>Oplopend</option></select></label>
        <label class="text-sm font-medium">Per pagina<select name="per_page" class="mt-1 w-full rounded-lg border-slate-300">@foreach([25,50,100] as $size)<option value="{{ $size }}" @selected($query->perPage() === $size)>{{ $size }}</option>@endforeach</select></label>
        <div class="flex items-end gap-3"><button class="rounded-lg bg-slate-900 px-4 py-3 font-semibold text-white">Filteren</button>@if($hasActiveFilters)<a href="{{ route('sales.quotations.index') }}" class="px-3 py-3 font-semibold text-blue-700">Wissen</a>@endif</div>
    </form>
    @if($quotations->items() === [])
        <p class="mt-6 rounded-xl bg-white p-8 text-center text-slate-600">{{ $hasActiveFilters ? 'Geen offertes gevonden met deze filters.' : 'Nog geen offertes.' }}</p>
    @else
        <div class="mt-6 hidden overflow-x-auto rounded-xl bg-white shadow-sm md:block"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr>@foreach(['Offertenummer','Klant','Offertedatum','Vervaldatum','Status','Valuta','Netto totaal'] as $heading)<th class="px-4 py-3">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y">@foreach($quotations->items() as $item)<tr><td class="px-4 py-3"><a class="font-semibold text-blue-700" href="{{ route('sales.quotations.show',$item->id()->toString()) }}">{{ $item->number()->value() }}</a></td><td class="px-4 py-3">{{ $item->customerName()->toString() }}</td><td class="px-4 py-3">{{ $item->quotationDate()->format('d-m-Y') }}</td><td class="px-4 py-3">{{ $item->expiryDate()?->format('d-m-Y') ?? '—' }}</td><td class="px-4 py-3">{{ $statusPresenter::label($item->status()) }}</td><td class="px-4 py-3">{{ $item->currency()->code() }}</td><td class="px-4 py-3">{{ $item->netTotal()->amount() }}</td></tr>@endforeach</tbody></table></div>
        <div class="mt-6 space-y-3 md:hidden">@foreach($quotations->items() as $item)<a href="{{ route('sales.quotations.show',$item->id()->toString()) }}" class="block rounded-xl bg-white p-4 shadow-sm"><span class="font-bold text-blue-700">{{ $item->number()->value() }}</span><span class="float-right">{{ $statusPresenter::label($item->status()) }}</span><p class="mt-2">{{ $item->customerName()->toString() }}</p><p class="text-sm text-slate-600">{{ $item->quotationDate()->format('d-m-Y') }} · {{ $item->currency()->code() }} {{ $item->netTotal()->amount() }}</p></a>@endforeach</div>
        @php($lastPage = max(1, (int) ceil($quotations->total() / $quotations->perPage())))
        <nav class="mt-6 flex justify-between" aria-label="Paginering">@if($quotations->page()>1)<a class="font-semibold text-blue-700" href="{{ route('sales.quotations.index',$queryParameters+['page'=>$quotations->page()-1]) }}">Vorige</a>@else<span></span>@endif<span>Pagina {{ $quotations->page() }} van {{ $lastPage }}</span>@if($quotations->page()<$lastPage)<a class="font-semibold text-blue-700" href="{{ route('sales.quotations.index',$queryParameters+['page'=>$quotations->page()+1]) }}">Volgende</a>@endif</nav>
    @endif
</x-layouts.app>
