<x-layouts.app :$domainUser :$administrationContext :$canViewRelations :$canViewSales title="Offerte {{ $quotation->number()->value() }}">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-medium text-slate-500">Offerte</p><h1 class="text-2xl font-bold">{{ $quotation->number()->value() }}</h1><p class="mt-1">{{ $statusPresenter::label($quotation->status()) }}</p></div>@if($canManageQuotations && $quotation->status() === \App\Domain\Sales\Enums\QuotationStatus::Draft)<a href="{{ route('sales.quotations.edit',$quotation->id()->toString()) }}" class="rounded-lg border border-blue-700 px-4 py-3 font-semibold text-blue-700">Header bewerken</a>@endif</div>
    <section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Offertegegevens</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-sm text-slate-500">Klantnummer</dt><dd class="font-semibold">{{ $quotation->customer()->customerNumber()->toString() }}</dd></div><div><dt class="text-sm text-slate-500">Klant</dt><dd class="font-semibold">{{ $quotation->customer()->displayName()->toString() }}</dd></div><div><dt class="text-sm text-slate-500">Offertedatum</dt><dd>{{ $quotation->quotationDate()->format('d-m-Y') }}</dd></div><div><dt class="text-sm text-slate-500">Vervaldatum</dt><dd>{{ $quotation->expiryDate()?->format('d-m-Y') ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Valuta</dt><dd>{{ $quotation->currency()->code() }}</dd></div><div><dt class="text-sm text-slate-500">Offerteadres</dt><dd>@if($quotation->documentAddress()){{ $quotation->documentAddress()->addressLine()->value() }}@if($quotation->documentAddress()->addressLine2())<br>{{ $quotation->documentAddress()->addressLine2()->value() }}@endif<br>{{ $quotation->documentAddress()->postalCode()->value() }} {{ $quotation->documentAddress()->city()->value() }}<br>{{ $quotation->documentAddress()->countryCode()->value() }}@else<span class="text-slate-500">Niet vastgelegd (legacy)</span>@endif</dd></div></dl></section>
    <section class="mt-6"><h2 class="text-lg font-bold">Regels</h2>
        @if($quotation->lines() === [])<p class="mt-3 rounded-xl bg-white p-5 text-slate-600">Nog geen regels.</p>@endif
        <div class="mt-3 space-y-4">@foreach($quotation->lines() as $line)<article class="rounded-xl bg-white p-5 shadow-sm"><div class="grid gap-3 md:grid-cols-[1fr_auto_auto_auto]"><div><h3 class="font-semibold">{{ $line->description()->value() }}</h3></div><p><span class="text-sm text-slate-500">Aantal</span><br>{{ $line->quantity()->value() }}</p><p><span class="text-sm text-slate-500">Prijs</span><br>{{ $line->unitPrice()->amount() }}</p><p><span class="text-sm text-slate-500">Totaal</span><br>{{ $line->lineTotal()->amount() }}</p></div>
            @if($canManageQuotations && $quotation->status() === \App\Domain\Sales\Enums\QuotationStatus::Draft)<details class="mt-4"><summary class="cursor-pointer font-semibold text-blue-700">Regel bewerken</summary><form method="POST" action="{{ route('sales.quotations.lines.update',[$quotation->id()->toString(),$line->id()->toString()]) }}" class="mt-3 grid gap-3 sm:grid-cols-3">@csrf @method('PUT')<label>Omschrijving<input name="description" required value="{{ $line->description()->value() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Aantal<input name="quantity" inputmode="decimal" required value="{{ $line->quantity()->value() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Prijs per eenheid<input name="unit_price" inputmode="decimal" required value="{{ $line->unitPrice()->amount() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white sm:col-span-3">Regel opslaan</button></form><form method="POST" action="{{ route('sales.quotations.lines.destroy',[$quotation->id()->toString(),$line->id()->toString()]) }}" class="mt-3">@csrf @method('DELETE')<button class="rounded-lg border border-red-700 px-4 py-3 font-semibold text-red-700">Regel verwijderen</button></form></details>@endif
        </article>@endforeach</div>
        <p class="mt-5 text-right text-lg font-bold">Netto totaal: {{ $quotation->currency()->code() }} {{ $quotation->total()->amount() }}</p>
    </section>
    @if($canManageQuotations && $quotation->status() === \App\Domain\Sales\Enums\QuotationStatus::Draft)<section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Regel toevoegen</h2><form method="POST" action="{{ route('sales.quotations.lines.store',$quotation->id()->toString()) }}" class="mt-4 grid gap-4 sm:grid-cols-3">@csrf<label>Omschrijving<input name="description" required value="{{ old('description') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('description')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Aantal<input name="quantity" inputmode="decimal" required value="{{ old('quantity') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('quantity')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Prijs per eenheid<input name="unit_price" inputmode="decimal" required value="{{ old('unit_price') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('unit_price')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white sm:col-span-3">Regel toevoegen</button></form></section>@endif
    @if($canManageQuotations)<section class="mt-6"><h2 class="text-lg font-bold">Acties</h2><div class="mt-3 flex flex-wrap gap-3">@if($quotation->status() === \App\Domain\Sales\Enums\QuotationStatus::Draft)<form method="POST" action="{{ route('sales.quotations.send',$quotation->id()->toString()) }}">@csrf<button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white">Offerte verzenden</button></form><form method="POST" action="{{ route('sales.quotations.expire',$quotation->id()->toString()) }}">@csrf<button class="rounded-lg border px-4 py-3 font-semibold">Offerte laten verlopen</button></form>@elseif($quotation->status() === \App\Domain\Sales\Enums\QuotationStatus::Sent)<form method="POST" action="{{ route('sales.quotations.accept',$quotation->id()->toString()) }}">@csrf<button class="rounded-lg bg-emerald-700 px-4 py-3 font-semibold text-white">Offerte accepteren</button></form><form method="POST" action="{{ route('sales.quotations.reject',$quotation->id()->toString()) }}">@csrf<button class="rounded-lg border border-red-700 px-4 py-3 font-semibold text-red-700">Offerte afwijzen</button></form><form method="POST" action="{{ route('sales.quotations.expire',$quotation->id()->toString()) }}">@csrf<button class="rounded-lg border px-4 py-3 font-semibold">Offerte laten verlopen</button></form>@endif</div></section>@endif
    @if($sourceOrderId !== null && $canViewSales)<section class="mt-6"><a href="{{ route('sales.orders.show',$sourceOrderId->toString()) }}" class="inline-flex rounded-lg border border-blue-700 px-4 py-3 font-semibold text-blue-700">Bekijk order</a></section>
    @elseif($canManageOrders && $quotation->status() === \App\Domain\Sales\Enums\QuotationStatus::Accepted)<section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Order maken</h2><form method="POST" action="{{ route('sales.quotations.order.store',$quotation->id()->toString()) }}" class="mt-4 flex flex-wrap items-end gap-4">@csrf<label for="order_date" class="font-semibold">Orderdatum<input id="order_date" name="order_date" type="date" required value="{{ old('order_date',$defaultOrderDate) }}" class="mt-1 block rounded-lg border-slate-300">@error('order_date')<span class="block text-sm text-red-700">{{ $message }}</span>@enderror</label><button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white">Order maken</button></form></section>@endif
</x-layouts.app>
