<x-layouts.app :domain-user="$domainUser" :administration-context="$administrationContext" title="Boekjaar {{ $year->code() }}">
    <div class="mx-auto max-w-6xl">
        <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-blue-700">Beheer → Grootboek → Perioden</p><h1 class="text-2xl font-bold">{{ $year->code() }} – {{ $year->label() }}</h1><p class="mt-2 text-sm text-slate-600">{{ $year->startDate()->format('d-m-Y') }} t/m {{ $year->endDate()->format('d-m-Y') }} · dekking {{ $year->hasFullCoverage() ? 'volledig' : 'onvolledig' }}</p></div>@if($canManage)<a class="rounded border px-4 py-3 font-semibold" href="{{ route('settings.accounting-periods.edit', $year->id()->toString()) }}">Label wijzigen</a>@endif</div>
        @if($readiness->status === \App\Application\Accounting\AccountingPeriodReadinessStatus::Success)<p class="mt-5 rounded-lg bg-emerald-50 p-4 text-emerald-900" role="status">Posting readiness: gereed.</p>@else<p class="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-900" role="status">Posting readiness: nog niet gereed. Boekingen zonder passende Open periode worden geweigerd.</p>@endif

        @if($canManage)<section class="mt-6 rounded-xl border bg-white p-6"><h2 class="text-lg font-bold">Periode expliciet toevoegen</h2><p class="mt-1 text-sm text-slate-600">Maak custom, aaneengesloten perioden die samen het volledige boekjaar dekken.</p><form method="POST" action="{{ route('settings.accounting-periods.periods.store', $year->id()->toString()) }}" class="mt-4 grid gap-4 md:grid-cols-2">@csrf
            @error('period')<p class="text-sm text-red-700 md:col-span-2" role="alert">{{ $message }}</p>@enderror
            <div><label for="code" class="font-semibold">Code</label><input id="code" name="code" value="{{ old('code') }}" required maxlength="50" class="mt-2 min-h-11 w-full rounded-lg border px-3"></div>
            <div><label for="label" class="font-semibold">Label</label><input id="label" name="label" value="{{ old('label') }}" required maxlength="100" class="mt-2 min-h-11 w-full rounded-lg border px-3"></div>
            <div><label for="start_date" class="font-semibold">Startdatum</label><input id="start_date" type="date" name="start_date" value="{{ old('start_date') }}" required class="mt-2 min-h-11 w-full rounded-lg border px-3"></div>
            <div><label for="end_date" class="font-semibold">Einddatum</label><input id="end_date" type="date" name="end_date" value="{{ old('end_date') }}" required class="mt-2 min-h-11 w-full rounded-lg border px-3"></div>
            <button class="min-h-11 rounded-lg bg-blue-700 px-5 py-2 text-white md:col-span-2">Periode toevoegen</button>
        </form></section>@endif

        @if($canReconfigure)<section class="mt-6 rounded-xl border border-amber-300 bg-amber-50 p-6"><h2 class="text-lg font-bold">Periodenindeling opnieuw inrichten</h2><p class="mt-2 text-sm text-amber-950">Vervang uitsluitend deze nog volledig Open periodenindeling door maandperioden. Financiële boekingen worden niet gewijzigd. Gesloten perioden of perioden met audithistorie zijn niet wijzigbaar.</p><form method="POST" action="{{ route('settings.accounting-periods.periods.replace', $year->id()->toString()) }}" class="mt-4">@csrf @foreach($year->periods() as $period)<input type="hidden" name="expected_period_ids[]" value="{{ $period->id()->toString() }}">@endforeach<button class="min-h-11 rounded-lg bg-amber-700 px-5 py-2 font-semibold text-white">12 maandperioden genereren</button></form></section>@endif

        <section class="mt-6 space-y-5"><h2 class="text-xl font-bold">Perioden en audit</h2>@forelse($year->periods() as $period)<article class="rounded-xl border bg-white p-5"><div class="flex flex-wrap justify-between gap-4"><div><h3 class="font-bold">{{ $period->code() }} – {{ $period->label() }}</h3><p class="text-sm text-slate-600">{{ $period->startDate()->format('d-m-Y') }} t/m {{ $period->endDate()->format('d-m-Y') }} · {{ $period->status()->value === 'open' ? 'Open' : 'Gesloten' }}</p></div>
            @if($period->status()->value === 'open' && $canClose)<form method="POST" action="{{ route('settings.accounting-periods.periods.close', [$year->id()->toString(), $period->id()->toString()]) }}" class="max-w-md">@csrf<label class="text-sm font-semibold" for="close_reason_{{ $period->id()->toString() }}">Reden voor sluiten</label><input id="close_reason_{{ $period->id()->toString() }}" name="reason" required maxlength="500" class="mt-1 min-h-11 w-full rounded border px-3"><p class="my-2 text-xs text-slate-600">Nieuwe boekingen met een boekingsdatum in deze periode worden geblokkeerd.</p><button class="rounded border px-3 py-2">Sluiten</button></form>@endif
            @if($period->status()->value === 'closed' && $canReopen)<form method="POST" action="{{ route('settings.accounting-periods.periods.reopen', [$year->id()->toString(), $period->id()->toString()]) }}" class="max-w-md">@csrf<label class="text-sm font-semibold" for="reopen_reason_{{ $period->id()->toString() }}">Reden voor heropenen</label><input id="reopen_reason_{{ $period->id()->toString() }}" name="reason" required maxlength="500" class="mt-1 min-h-11 w-full rounded border px-3"><p class="my-2 text-xs text-slate-600">Boekingen met een boekingsdatum in deze periode zijn daarna weer toegestaan.</p><button class="rounded border px-3 py-2">Heropenen</button></form>@endif</div>
            <h4 class="mt-5 font-semibold">Statusgeschiedenis</h4><ol class="mt-2 space-y-2 text-sm">@forelse($histories[$period->id()->toString()]?->history ?? [] as $entry)<li class="rounded bg-slate-50 p-3">{{ ucfirst($entry->fromStatus->value) }} → {{ ucfirst($entry->toStatus->value) }} · {{ $entry->reason }} · actor {{ $entry->actor->toString() }} · {{ $entry->occurredAt->format('d-m-Y H:i:s') }}</li>@empty<li class="text-slate-600">Nog geen statuswijzigingen.</li>@endforelse</ol>
        </article>@empty<p class="rounded-xl border bg-white p-5 text-slate-600">Nog geen perioden ingericht.</p>@endforelse</section>
    </div>
</x-layouts.app>
