<x-layouts.app :$domainUser :$administrationContext :$canViewRelations :title="$contact->name->toString()">
    <nav aria-label="Kruimelpad" class="text-sm text-slate-600"><a href="{{ route('relations.show', $relation->id()->toString()) }}" class="font-medium text-blue-700 hover:underline focus:ring-2 focus:ring-blue-700">{{ $relation->displayName()->toString() }}</a><span aria-hidden="true"> / </span><span aria-current="page">{{ $contact->name->toString() }}</span></nav>
    <article class="mt-4 max-w-3xl rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm text-slate-600">Contactpersoon van {{ $relation->displayName()->toString() }}</p><h1 class="mt-1 text-2xl font-semibold">{{ $contact->name->toString() }}</h1></div><span class="rounded-full bg-slate-100 px-3 py-1 font-medium">{{ $contact->status->value === 'active' ? 'Actief' : 'Inactief' }}</span></div>
        <dl class="mt-6 grid gap-4 sm:grid-cols-2"><div><dt class="font-medium text-slate-600">E-mail</dt><dd class="mt-1">{{ $contact->emailAddress?->toString() ?? 'Niet opgegeven' }}</dd></div><div><dt class="font-medium text-slate-600">Telefoon</dt><dd class="mt-1">{{ $contact->phoneNumber?->toString() ?? 'Niet opgegeven' }}</dd></div></dl>
        @if($canUpdateRelations)<div class="mt-6 flex flex-wrap gap-3"><a href="{{ route('relations.contacts.edit', [$relation->id()->toString(), $contact->id->toString()]) }}" class="inline-flex min-h-11 items-center rounded-lg bg-blue-700 px-4 font-semibold text-white focus:ring-2 focus:ring-blue-700 focus:ring-offset-2">Contactpersoon bewerken</a>@if($contact->status->value === 'active')<form method="POST" action="{{ route('relations.contacts.deactivate', [$relation->id()->toString(), $contact->id->toString()]) }}">@csrf @method('DELETE')<button class="min-h-11 rounded-lg border border-red-300 px-4 font-semibold text-red-800 focus:ring-2 focus:ring-red-700">Contactpersoon deactiveren</button></form>@else<form method="POST" action="{{ route('relations.contacts.activate', [$relation->id()->toString(), $contact->id->toString()]) }}">@csrf<button class="min-h-11 rounded-lg border border-emerald-400 px-4 font-semibold text-emerald-800 focus:ring-2 focus:ring-emerald-700">Contactpersoon activeren</button></form>@endif</div>@endif
    </article>
    <p class="mt-6"><a href="{{ route('relations.show', $relation->id()->toString()) }}" class="inline-flex min-h-11 items-center font-semibold text-blue-700 focus:ring-2 focus:ring-blue-700">Terug naar relatie</a></p>
</x-layouts.app>
