@if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-red-800"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@php($existing=$invoice?->lines() ?? [])
<section class="grid gap-4 rounded-xl bg-white p-6 shadow-sm md:grid-cols-2">
<label>Leverancier<select required name="supplier_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Selecteer expliciet</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->supplierId->toString() }}" @selected(old('supplier_id',$invoice?->supplierId()->toString())===$supplier->supplierId->toString())>{{ $supplier->supplierNumber->toString() }} · {{ $supplier->name->toString() }}</option>@endforeach</select></label>
<label>Leveranciersfactuurnummer<input required name="supplier_invoice_number" value="{{ old('supplier_invoice_number',$invoice?->supplierInvoiceNumber()->value()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
@foreach(['invoice_date'=>'Factuurdatum','received_date'=>'Ontvangstdatum','supply_date'=>'Prestatiedatum (optioneel)','due_date'=>'Vervaldatum'] as $name=>$label)<label>{{ $label }}<input type="date" name="{{ $name }}" @required($name!=='supply_date') value="{{ old($name, match($name){'invoice_date'=>$invoice?->supplierInvoiceDate()->format('Y-m-d'),'received_date'=>$invoice?->receivedDate()->format('Y-m-d'),'supply_date'=>$invoice?->supplyDate()?->format('Y-m-d'),'due_date'=>$invoice?->dueDate()->format('Y-m-d')}) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>@endforeach
<label>Valuta<input readonly value="EUR" class="mt-1 w-full rounded-lg border-slate-300 bg-slate-100"><input type="hidden" name="currency" value="EUR"></label>
</section>
<section class="grid gap-4 rounded-xl bg-white p-6 shadow-sm md:grid-cols-2"><h2 class="md:col-span-2 text-lg font-bold">Documentadres</h2><label>Adresregel 1<input required name="address_line_1" value="{{ old('address_line_1',$invoice?->documentAddress()->line1->value()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Adresregel 2<input name="address_line_2" value="{{ old('address_line_2',$invoice?->documentAddress()->line2?->value()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Postcode<input required name="postal_code" value="{{ old('postal_code',$invoice?->documentAddress()->postalCode->value()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Plaats<input required name="city" value="{{ old('city',$invoice?->documentAddress()->city->value()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Landcode<input required maxlength="2" name="country_code" value="{{ old('country_code',$invoice?->documentAddress()->countryCode->value()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label></section>
<section class="space-y-4 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Regels</h2><p class="text-sm text-slate-600">Selecteer rekening en btw-code expliciet. Markeer een bestaande regel voor verwijderen.</p>
@for($i=0;$i<max(3,count($existing)+1);$i++) @php($line=$existing[$i]??null)<div class="grid gap-3 border-t pt-4 md:grid-cols-6"><label class="md:col-span-2">Omschrijving<input name="lines[{{$i}}][description]" value="{{ old("lines.$i.description",$line?->description()->value()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Hoeveelheid<input name="lines[{{$i}}][quantity]" value="{{ old("lines.$i.quantity",$line?->quantity()->value()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Netto prijs<input name="lines[{{$i}}][unit_price]" value="{{ old("lines.$i.unit_price",$line?->unitPrice()->amount()) }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Rekening<select name="lines[{{$i}}][ledger_account_id]" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Selecteer</option>@foreach($accounts as $account)<option value="{{ $account->id()->toString() }}" @selected(old("lines.$i.ledger_account_id",$line?->account()->id->toString())===$account->id()->toString())>{{ $account->code()->value() }} · {{ $account->name()->value() }} ({{ $account->type()->value }})</option>@endforeach</select></label><label>Btw-code<select name="lines[{{$i}}][tax_code_id]" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Selecteer</option>@foreach($tax_codes as $tax)<option value="{{ $tax->id()->toString() }}" @selected(old("lines.$i.tax_code_id",$line?->tax()->id->toString())===$tax->id()->toString())>{{ $tax->code()->value() }} · {{ $tax->name()->value() }} · {{ $tax->treatment()->value }}</option>@endforeach</select><input type="hidden" name="lines[{{$i}}][fully_deductible]" value="1"></label>@if($line)<label class="md:col-span-6"><input type="checkbox" name="lines[{{$i}}][_delete]" value="1"> Regel verwijderen</label>@endif</div>@endfor</section>
