<x-layouts.app :$domainUser :$administrationContext :$canViewRelations :$canViewSales title="Factuur maken voor {{ $order->number()->value() }}">
    <div><p class="text-sm font-medium text-slate-500">Order {{ $order->number()->value() }}</p><h1 class="text-2xl font-bold">Verkoopfactuur maken</h1><p class="mt-1">{{ $statusPresenter::label($order->status()) }} · {{ $order->customer()->customerNumber()->toString() }} · {{ $order->customer()->displayName()->toString() }} · {{ $order->currency()->code() }}</p></div>
    @if($invoiceAddresses===[])<div class="mt-6 rounded-xl bg-amber-50 p-5 text-amber-900" role="alert"><strong>Geen geldig factuuradres beschikbaar.</strong> Voeg eerst een actief factuuradres toe voor deze relatie.</div>@endif
    @if($taxCodes===[])<div class="mt-6 rounded-xl bg-amber-50 p-5 text-amber-900" role="alert"><strong>Geen btw-codes beschikbaar.</strong> Configureer eerst een actieve verkoop-btw-code.</div>@endif
    @error('invoice')<div class="mt-6 rounded-xl bg-red-50 p-5 text-red-800" role="alert">{{ $message }}</div>@enderror
    <form method="POST" action="{{ route('sales.orders.invoice.store',$order->id()->toString()) }}" class="mt-6 space-y-6">@csrf
        <input type="hidden" name="draft_request_token" value="{{ old('draft_request_token',$draftRequestToken) }}">
        @error('draft_request_token')<p class="text-sm text-red-700" role="alert">{{ $message }}</p>@enderror
        <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Factuurgegevens</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label>Factuurdatum<input type="date" name="invoice_date" required value="{{ old('invoice_date',now()->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-slate-300">@error('invoice_date')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Vervaldatum<input type="date" name="due_date" required value="{{ old('due_date',now()->addDays(30)->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-slate-300">@error('due_date')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Prestatiedatum <span class="text-sm text-slate-500">(optioneel voor Nederlandse btw)</span><input type="date" name="supply_date" value="{{ old('supply_date') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('supply_date')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label class="sm:col-span-2">Factuuradres<select name="invoice_address_id" required class="mt-1 w-full rounded-lg border-slate-300"><option value="">Selecteer een factuuradres</option>@foreach($invoiceAddresses as $address)<option value="{{ $address->id->toString() }}" @selected(old('invoice_address_id')===$address->id->toString())>{{ $address->addressLine->value() }} · {{ $address->postalCode->value() }} {{ $address->city->value() }}</option>@endforeach</select>@error('invoice_address_id')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label></div></section>
        <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Te factureren regels</h2>@error('lines')<p class="mt-2 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror
            <div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="hidden md:table-header-group"><tr>@foreach(['Omschrijving','Besteld','Gereserveerd','Gefactureerd','Beschikbaar','Factureren','Btw-code'] as $heading)<th scope="col" class="px-3 py-2">{{ $heading }}</th>@endforeach</tr></thead><tbody class="block space-y-4 md:table-row-group md:space-y-0">@foreach($order->lines() as $line) @php($p=$progressByLine[$line->id()->toString()])<tr class="block rounded-lg border p-4 md:table-row md:rounded-none md:border-0 md:p-0"><th scope="row" class="block px-3 py-2 text-base md:table-cell md:py-3">{{ $line->description()->value() }}</th><td class="grid grid-cols-2 px-3 py-1 md:table-cell md:py-3"><span class="md:hidden">Besteld</span>{{ $p->ordered()->value() }}</td><td class="grid grid-cols-2 px-3 py-1 md:table-cell md:py-3"><span class="md:hidden">Gereserveerd</span>{{ $p->reserved()->value() }}</td><td class="grid grid-cols-2 px-3 py-1 md:table-cell md:py-3"><span class="md:hidden">Gefactureerd</span>{{ $p->allocated()->value() }}</td><td class="grid grid-cols-2 px-3 py-1 md:table-cell md:py-3"><span class="md:hidden">Beschikbaar</span>{{ $p->available()->value() }}</td><td class="block px-3 py-2 md:table-cell md:py-3"><label for="quantity-{{ $line->id()->toString() }}" class="block text-sm md:sr-only">Hoeveelheid</label><input id="quantity-{{ $line->id()->toString() }}" name="lines[{{ $line->id()->toString() }}][quantity]" inputmode="decimal" value="{{ old('lines.'.$line->id()->toString().'.quantity',$p->available()->value()) }}" class="mt-1 w-full rounded-lg border-slate-300 md:mt-0 md:w-32">@error('lines.'.$line->id()->toString().'.quantity')<span class="block text-sm text-red-700">{{ $message }}</span>@enderror</td><td class="block px-3 py-2 md:table-cell md:py-3"><label for="tax-{{ $line->id()->toString() }}" class="block text-sm md:sr-only">Btw-code</label><select id="tax-{{ $line->id()->toString() }}" name="lines[{{ $line->id()->toString() }}][tax_code_id]" class="mt-1 w-full rounded-lg border-slate-300 md:mt-0"><option value="">Selecteer btw</option>@foreach($taxCodes as $taxCode)<option value="{{ $taxCode->id()->toString() }}" @selected(old('lines.'.$line->id()->toString().'.tax_code_id')===$taxCode->id()->toString())>{{ $taxCode->code()->value() }} · {{ $taxCode->name()->value() }} · {{ $taxCode->rate()->value() }}%</option>@endforeach</select>@error('lines.'.$line->id()->toString().'.tax_code_id')<span class="block text-sm text-red-700">{{ $message }}</span>@enderror</td></tr>@endforeach</tbody></table></div>
        </section>
        <button @disabled($invoiceAddresses===[] || $taxCodes===[]) class="rounded-lg bg-blue-700 px-5 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-400">Draft factuur maken</button>
    </form>
</x-layouts.app>
