<x-layouts.app :$domainUser :$administrationContext :$canViewRelations :$canViewSales title="Order {{ $order->number()->value() }}">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-medium text-slate-500">Order</p><h1 class="text-2xl font-bold">{{ $order->number()->value() }}</h1><p class="mt-1">{{ $statusPresenter::label($order->status()) }}</p></div><div class="flex flex-wrap gap-3">@if($canCreateInvoice)<a href="{{ route('sales.orders.invoice.create',$order->id()->toString()) }}" class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white">Factuur maken</a>@endif @if($canManageOrders && $order->status() === \App\Domain\Sales\Enums\OrderStatus::Draft)<a href="{{ route('sales.orders.edit',$order->id()->toString()) }}" class="rounded-lg border border-blue-700 px-4 py-3 font-semibold text-blue-700">Header bewerken</a>@endif</div></div>
    <section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Ordergegevens</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-sm text-slate-500">Klantnummer</dt><dd class="font-semibold">{{ $order->customer()->customerNumber()->toString() }}</dd></div><div><dt class="text-sm text-slate-500">Klant</dt><dd class="font-semibold">{{ $order->customer()->displayName()->toString() }}</dd></div><div><dt class="text-sm text-slate-500">Orderdatum</dt><dd>{{ $order->orderDate()->format('d-m-Y') }}</dd></div><div><dt class="text-sm text-slate-500">Bronofferte</dt><dd>@if($order->sourceQuotationId())<a class="text-blue-700" href="{{ route("sales.quotations.show", $order->sourceQuotationId()->toString()) }}">{{ $order->sourceQuotationId()->toString() }}</a>@else Geen bronofferte @endif</dd></div><div><dt class="text-sm text-slate-500">Valuta</dt><dd>{{ $order->currency()->code() }}</dd></div></dl></section>
    <section class="mt-6"><h2 class="text-lg font-bold">Regels</h2>
        @if($order->lines() === [])<p class="mt-3 rounded-xl bg-white p-5 text-slate-600">Nog geen regels.</p>@endif
        <div class="mt-3 hidden overflow-x-auto md:block"><table class="w-full bg-white text-left text-sm shadow-sm"><thead><tr>@foreach(['Omschrijving','Besteld','Gereserveerd','Gefactureerd','Beschikbaar','Prijs','Totaal'] as $heading)<th scope="col" class="px-4 py-3">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y">@foreach($order->lines() as $line) @php($lineProgress=$progressByLine[$line->id()->toString()])<tr><td class="px-4 py-3 font-semibold">{{ $line->description()->value() }}</td><td class="px-4 py-3">{{ $lineProgress->ordered()->value() }}</td><td class="px-4 py-3">{{ $lineProgress->reserved()->value() }}</td><td class="px-4 py-3">{{ $lineProgress->allocated()->value() }}</td><td class="px-4 py-3">{{ $lineProgress->available()->value() }}</td><td class="px-4 py-3">{{ $line->unitPrice()->amount() }}</td><td class="px-4 py-3">{{ $line->lineTotal()->amount() }}</td></tr>@endforeach</tbody></table></div>
        <div class="mt-3 space-y-4 md:hidden">@foreach($order->lines() as $line) @php($lineProgress=$progressByLine[$line->id()->toString()])<article class="rounded-xl bg-white p-5 shadow-sm"><h3 class="font-semibold">{{ $line->description()->value() }}</h3><dl class="mt-3 grid grid-cols-2 gap-3"><div><dt class="text-sm text-slate-500">Besteld</dt><dd>{{ $lineProgress->ordered()->value() }}</dd></div><div><dt class="text-sm text-slate-500">Gereserveerd</dt><dd>{{ $lineProgress->reserved()->value() }}</dd></div><div><dt class="text-sm text-slate-500">Gefactureerd</dt><dd>{{ $lineProgress->allocated()->value() }}</dd></div><div><dt class="text-sm text-slate-500">Beschikbaar</dt><dd>{{ $lineProgress->available()->value() }}</dd></div></dl>
            @if($canManageOrders && $order->status() === \App\Domain\Sales\Enums\OrderStatus::Draft)<details class="mt-4"><summary class="cursor-pointer font-semibold text-blue-700">Regel bewerken</summary><form method="POST" action="{{ route('sales.orders.lines.update',[$order->id()->toString(),$line->id()->toString()]) }}" class="mt-3 grid gap-3 sm:grid-cols-3">@csrf @method('PUT')<label>Omschrijving<input name="description" required value="{{ $line->description()->value() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Aantal<input name="quantity" inputmode="decimal" required value="{{ $line->quantity()->value() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Prijs per eenheid<input name="unit_price" inputmode="decimal" required value="{{ $line->unitPrice()->amount() }}" class="mt-1 w-full rounded-lg border-slate-300"></label><button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white sm:col-span-3">Regel opslaan</button></form><form method="POST" action="{{ route('sales.orders.lines.destroy',[$order->id()->toString(),$line->id()->toString()]) }}" class="mt-3">@csrf @method('DELETE')<button class="rounded-lg border border-red-700 px-4 py-3 font-semibold text-red-700">Regel verwijderen</button></form></details>@endif
        </article>@endforeach</div>
        <p class="mt-5 text-right text-lg font-bold">Netto totaal: {{ $order->currency()->code() }} {{ $order->total()->amount() }}</p>
    </section>
    @if($canManageOrders && $order->status() === \App\Domain\Sales\Enums\OrderStatus::Draft)<section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Regel toevoegen</h2><form method="POST" action="{{ route('sales.orders.lines.store',$order->id()->toString()) }}" class="mt-4 grid gap-4 sm:grid-cols-3">@csrf<label>Omschrijving<input name="description" required value="{{ old('description') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('description')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Aantal<input name="quantity" inputmode="decimal" required value="{{ old('quantity') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('quantity')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><label>Prijs per eenheid<input name="unit_price" inputmode="decimal" required value="{{ old('unit_price') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('unit_price')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white sm:col-span-3">Regel toevoegen</button></form></section>@endif
    @if($canManageOrders && in_array($order->status(), [\App\Domain\Sales\Enums\OrderStatus::Draft, \App\Domain\Sales\Enums\OrderStatus::Confirmed], true))
        <section class="mt-6"><h2 class="text-lg font-bold">Acties</h2><div class="mt-3 flex flex-wrap gap-3">
            @if($order->status() === \App\Domain\Sales\Enums\OrderStatus::Draft)<form method="POST" action="{{ route('sales.orders.confirm',$order->id()->toString()) }}">@csrf<button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white">Order bevestigen</button></form>@endif
            <form method="POST" action="{{ route('sales.orders.cancel',$order->id()->toString()) }}">@csrf<button class="rounded-lg border border-red-700 px-4 py-3 font-semibold text-red-700">Order annuleren</button></form>
        </div></section>
    @endif
</x-layouts.app>
