<x-layouts.app :domain-user="$domainUser" :administration-context="$administrationContext" title="Bankreconciliatie">
    <div><h1 class="text-2xl font-bold">Te verwerken bankmutaties</h1><p class="mt-1 text-slate-600">Selecteer intentie en allocaties; importeren alleen maakt nooit financiële boekingen.</p></div>
    <form method="GET" action="{{ route('banking.reconciliation.index') }}" class="mt-6 grid gap-3 rounded-xl bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-4">
        <label>Bankrekening<select name="bank_account_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Alle</option>@foreach($bankAccounts as $account)<option value="{{ $account->id()->toString() }}" @selected(($filters['bank_account_id']??'')===$account->id()->toString())>{{ $account->label()->value() }}</option>@endforeach</select></label>
        <label>Van<input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Tot<input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
        <label>Richting<select name="direction" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Alle</option><option value="CRDT" @selected(($filters['direction']??'')==='CRDT')>Inkomend</option><option value="DBIT" @selected(($filters['direction']??'')==='DBIT')>Uitgaand</option></select></label>
        <label>Status<select name="state" class="mt-1 w-full rounded-lg border-slate-300">@foreach($states as $state)<option value="{{ $state->value }}" @selected(($filters['state']??'unresolved')===$state->value)>{{ ucfirst(str_replace('_',' ',$state->value)) }}</option>@endforeach</select></label>
        <label>Exact bedrag<input name="amount" inputmode="decimal" value="{{ $filters['amount'] ?? '' }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="sm:col-span-2">Zoeken<input name="search" maxlength="255" value="{{ $filters['search'] ?? '' }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
        <button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white">Filteren</button>
    </form>
    <div class="mt-6 overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full text-left"><thead><tr class="border-b"><th class="p-4">Datum</th><th class="p-4">Bedrag</th><th class="p-4">Tegenpartij / referentie</th><th class="p-4">Status</th><th class="p-4">Suggestie</th></tr></thead><tbody>@forelse($items as $item)<tr class="border-b"><td class="p-4"><a class="font-semibold text-blue-700" href="{{ route('banking.reconciliation.show',$item->source->entry->id->toString()) }}">{{ $item->source->entry->bookingDate->format('d-m-Y') }}</a></td><td class="p-4">{{ $moneyFormatter->format($item->source->entry->amount) }}</td><td class="p-4"><span class="block">{{ $item->source->entry->counterpartyName ?? 'Onbekend' }}</span><span class="text-xs text-slate-500">{{ $item->source->entry->accountServicerReference ?? $item->source->entry->entryReference ?? implode(' · ',$item->source->entry->remittanceLines) }}</span></td><td class="p-4">{{ ucfirst($item->source->state->value) }}</td><td class="p-4">@if($item->suggestion){{ $item->suggestion->intent->value }} · {{ $item->suggestion->confidence->value / 100 }}%<span class="block text-xs text-slate-500">{{ implode(' · ',$item->suggestion->evidence) }}</span>@else—@endif</td></tr>@empty<tr><td colspan="5" class="p-6 text-slate-600">Geen bankmutaties voor deze filters.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $items->links() }}</div>
</x-layouts.app>
