<x-layouts.app :domain-user="$domainUser" :administration-context="$administrationContext" title="Bankmutatie">
    @php($entry=$source->entry)
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-blue-700">Immutable CAMT-bron</p><h1 class="text-2xl font-bold">Bankmutatie {{ $entry->accountServicerReference ?? $entry->entryReference ?? $entry->id->toString() }}</h1><p class="mt-1">{{ ucfirst($source->state->value) }} · {{ $moneyFormatter->format($entry->amount) }}</p></div><a class="font-semibold text-blue-700" href="{{ route('banking.reconciliation.index') }}">Terug naar werkvoorraad</a></div>
    <section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Bronfeiten en provenance</h2><dl class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><div><dt class="text-sm text-slate-500">Booking date</dt><dd>{{ $entry->bookingDate->format('d-m-Y') }}</dd></div><div><dt class="text-sm text-slate-500">Value date</dt><dd>{{ $entry->valueDate?->format('d-m-Y') ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Richting</dt><dd>{{ $entry->direction->value==='CRDT'?'Inkomend':'Uitgaand' }}</dd></div><div><dt class="text-sm text-slate-500">Tegenpartij</dt><dd>{{ $entry->counterpartyName ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">IBAN/rekening</dt><dd>{{ $entry->counterpartyAccount ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Afschrift</dt><dd>{{ $source->statementExternalId ?? $source->statementId->toString() }}</dd></div><div class="sm:col-span-2"><dt class="text-sm text-slate-500">Omschrijving/referenties</dt><dd>{{ implode(' · ',array_filter([$entry->entryReference,$entry->endToEndId,$entry->creditorReference,...$entry->remittanceLines])) ?: '—' }}</dd></div></dl></section>

    @if($source->financial)<section class="mt-6 rounded-xl border border-emerald-200 bg-white p-6"><h2 class="text-lg font-bold">{{ $source->state===\App\Application\Banking\BankEntryDerivedState::Reversed?'Teruggedraaide':'Gereconcilede' }} financiële waarheid</h2><dl class="mt-3 grid gap-2 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Intentie</dt><dd>{{ $source->financial->intent->value }}</dd></div><div><dt class="text-sm text-slate-500">PostingDate</dt><dd>{{ $source->financial->postingDate->value()->format('d-m-Y') }}</dd></div><div><dt class="text-sm text-slate-500">BankTransaction</dt><dd class="font-mono text-xs">{{ $source->financial->bankTransactionId->toString() }}</dd></div><div><dt class="text-sm text-slate-500">JournalEntry</dt><dd class="font-mono text-xs">{{ $source->financial->journalEntryId->toString() }}</dd></div><div><dt class="text-sm text-slate-500">Allocaties</dt><dd>{{ count($source->financial->allocations) }}</dd></div>@if($source->financial->otherContraAccountId)<div><dt class="text-sm text-slate-500">Tegenrekening</dt><dd class="font-mono text-xs">{{ $source->financial->otherContraAccountId->toString() }}</dd></div>@endif @if($source->financial->reversalId)<div><dt class="text-sm text-slate-500">Reversal</dt><dd class="font-mono text-xs">{{ $source->financial->reversalId->toString() }}</dd></div>@endif</dl>
        @if($source->state===\App\Application\Banking\BankEntryDerivedState::Reconciled && $canReverse)<a class="mt-4 inline-block rounded-lg border border-red-700 px-4 py-3 font-semibold text-red-700" href="{{ route('banking.reconciliation.reverse.create',$entry->id->toString()) }}">Boeking corrigeren / terugdraaien</a>@endif
        @if($source->state===\App\Application\Banking\BankEntryDerivedState::Reversed)<p class="mt-4 rounded-lg bg-blue-50 p-3 text-blue-900">De eerdere reconciliation blijft historisch bestaan. Opnieuw reconciliëren creëert nieuwe financiële waarheid; de bron blijft ongewijzigd.</p>@endif
    </section>@endif

    @if($canReconcile && in_array($source->state,[\App\Application\Banking\BankEntryDerivedState::Unresolved,\App\Application\Banking\BankEntryDerivedState::Reversed],true))<section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">{{ $source->state===\App\Application\Banking\BankEntryDerivedState::Reversed?'Opnieuw reconciliëren':'Reconcile en boek' }}</h2><p class="mt-1 text-sm text-slate-600">Selectie bereidt de boeking voor. Definitief boeken vereist daarnaast BANKING.IMPORT_POST.</p><form method="POST" action="{{ route('banking.reconciliation.post',$entry->id->toString()) }}" class="mt-4 grid gap-4">@csrf
        <label>Intentie<select name="intent" required class="mt-1 w-full rounded-lg border-slate-300">@if($entry->direction->value==='CRDT')<option value="customer_receipt" @selected(old('intent')==='customer_receipt')>Klantontvangst</option>@else<option value="supplier_payment" @selected(old('intent')==='supplier_payment')>Leveranciersbetaling</option>@endif<option value="other" @selected(old('intent')==='other')>Overige transactie</option></select></label>
        <label>PostingDate<input type="date" name="posting_date" required value="{{ old('posting_date',$entry->bookingDate->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
        <label>Relatie-ID<select name="relation_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Selecteer voor betaling</option>@foreach(collect($candidates)->unique(fn($candidate)=>$candidate->relationId->toString()) as $candidate)<option value="{{ $candidate->relationId->toString() }}" @selected(old('relation_id')===$candidate->relationId->toString())>{{ $candidate->relationName }}</option>@endforeach</select></label>
        <fieldset class="rounded-lg border p-4"><legend class="font-semibold">Eligible openstaande posten</legend><div class="mt-2 space-y-3">@forelse($candidates as $index=>$candidate)<div class="grid gap-2 sm:grid-cols-[1fr_12rem]"><label><input type="checkbox" name="allocations[{{ $index }}][open_item_id]" value="{{ $candidate->openItemId->toString() }}" @checked(old("allocations.$index.open_item_id")===$candidate->openItemId->toString())> {{ $candidate->relationName }} · {{ $candidate->documentReference }} · open {{ $moneyFormatter->format($candidate->openBalance) }}</label><input name="allocations[{{ $index }}][amount]" inputmode="decimal" value="{{ old("allocations.$index.amount") }}" placeholder="Bedrag" class="rounded-lg border-slate-300"></div>@empty<p class="text-sm text-slate-600">Geen eligible openstaande posten.</p>@endforelse</div></fieldset>
        <label>Tegenrekening voor Overige<select name="contra_ledger_account_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Selecteer</option>@foreach($accounts as $account)<option value="{{ $account->id()->toString() }}" @selected(old('contra_ledger_account_id')===$account->id()->toString())>{{ $account->code()->value() }} · {{ $account->name()->toString() }}</option>@endforeach</select></label>
        <label>Beschrijving (optioneel)<input name="description" maxlength="1000" value="{{ old('description') }}" class="mt-1 w-full rounded-lg border-slate-300"><span class="block text-xs text-slate-500">De financiële omschrijving blijft server-owned en wordt uit de immutable bankbron afgeleid.</span></label>
        @if($canPost)<button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white">Definitief reconcile en boek</button>@else<p class="rounded-lg bg-amber-50 p-3 text-amber-900">U mag voorbereiden, maar niet definitief boeken.</p>@endif
    </form></section>@endif

    @if($canReconcile && $source->state===\App\Application\Banking\BankEntryDerivedState::Ignored)<section class="mt-6 rounded-xl bg-white p-6"><h2 class="font-bold">Herstellen</h2><form method="POST" action="{{ route('banking.reconciliation.restore',$entry->id->toString()) }}" class="mt-3 flex flex-col gap-3">@csrf<textarea name="reason" required maxlength="500" class="rounded-lg border-slate-300" placeholder="Reden">{{ old('reason') }}</textarea><button class="rounded-lg border px-4 py-3 font-semibold">Terugzetten naar Te verwerken</button></form></section>@elseif($canReconcile && $source->state===\App\Application\Banking\BankEntryDerivedState::Unresolved)<section class="mt-6 rounded-xl bg-white p-6"><h2 class="font-bold">Negeren</h2><form method="POST" action="{{ route('banking.reconciliation.ignore',$entry->id->toString()) }}" class="mt-3 flex flex-col gap-3">@csrf<textarea name="reason" required maxlength="500" class="rounded-lg border-slate-300" placeholder="Reden">{{ old('reason') }}</textarea><button class="rounded-lg border px-4 py-3 font-semibold">Bankmutatie negeren</button></form></section>@endif
    @if($source->manualHistory!==[])<section class="mt-6 rounded-xl bg-white p-6"><h2 class="font-bold">Handmatige geschiedenis</h2><ol class="mt-3 space-y-2">@foreach($source->manualHistory as $event)<li>{{ $event->occurredAt->format('d-m-Y H:i:s') }} · {{ $event->action->value }} · {{ $event->reason->value }} · actor {{ $event->actorId->toString() }}</li>@endforeach</ol></section>@endif
</x-layouts.app>
