<x-layouts.app :$domainUser :$administrationContext :$canViewRelations :$canViewSales title="Nieuwe creditfactuur">
    <h1 class="text-2xl font-bold">Nieuwe creditfactuur</h1>
    <div class="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950" role="note"><p class="font-bold">Volledige credit</p><p>De creditfactuur wordt volledig gebaseerd op de oorspronkelijke factuur. Gedeeltelijke credits en regelwijzigingen worden niet ondersteund.</p></div>
    <form method="GET" action="{{ route('sales.credit-invoices.create') }}" class="mt-6 flex flex-wrap items-end gap-3 rounded-xl bg-white p-4 shadow-sm"><label class="min-w-64 flex-1">Zoek bronfactuur<input name="source_q" value="{{ $sourceQuery }}" class="mt-1 w-full rounded-lg border-slate-300" placeholder="Factuurnummer of historische klantnaam"></label><button class="rounded-lg bg-slate-900 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-slate-900">Zoeken</button>@if($sourceQuery)<a href="{{ route('sales.credit-invoices.create') }}" class="px-3 py-3 font-semibold text-blue-700">Wissen</a>@endif</form>
    <form method="POST" action="{{ route('sales.credit-invoices.store') }}" class="mt-6 space-y-5">@csrf
        <fieldset><legend class="text-lg font-bold">Geschikte bronfactuur</legend>@error('source_invoice_id')<p class="mt-2 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror
            @if($sources->total()===0)<p class="mt-3 rounded-xl bg-white p-6 shadow-sm">Geen geschikte bronfacturen gevonden.</p>@else<div class="mt-3 grid gap-3 lg:grid-cols-2">@foreach($sources->items() as $source)<label class="cursor-pointer rounded-xl bg-white p-4 shadow-sm focus-within:ring-2 focus-within:ring-blue-700"><input type="radio" name="source_invoice_id" value="{{ $source->id()->toString() }}" @checked(old('source_invoice_id')===$source->id()->toString()) required><span class="ml-2 font-bold">{{ $source->number()->value() }}</span><span class="float-right">{{ $source->status()->value === 'paid' ? 'Betaald' : 'Geboekt' }}</span><p class="mt-2">{{ $source->customerName()->toString() }}</p><p class="text-sm text-slate-600">{{ $source->invoiceDate()->format('d-m-Y') }} · {{ $source->currency()->code() }}</p><p class="mt-2 font-semibold">Bruto {{ $moneyFormatter->format($source->grossTotal()) }}</p></label>@endforeach</div>@endif
        </fieldset>
        @if($sources->total()>0)<label class="block max-w-sm font-semibold">Creditdatum<input type="date" name="credit_date" value="{{ old('credit_date',now()->format('Y-m-d')) }}" required class="mt-1 w-full rounded-lg border-slate-300">@error('credit_date')<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label><button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-blue-700">Volledige creditfactuur aanmaken</button>@endif
    </form>
    @php($lastPage=max(1,(int)ceil($sources->total()/$sources->perPage())))
    @if($lastPage>1)<nav class="mt-6 flex justify-between" aria-label="Bronfactuurpaginering">@if($sources->page()>1)<a class="font-semibold text-blue-700" href="{{ route('sales.credit-invoices.create',array_filter(['source_q'=>$sourceQuery,'source_page'=>$sources->page()-1])) }}">Vorige</a>@else<span></span>@endif<span>Pagina {{ $sources->page() }} van {{ $lastPage }}</span>@if($sources->page()<$lastPage)<a class="font-semibold text-blue-700" href="{{ route('sales.credit-invoices.create',array_filter(['source_q'=>$sourceQuery,'source_page'=>$sources->page()+1])) }}">Volgende</a>@endif</nav>@endif
</x-layouts.app>
