<x-layouts.app :$domainUser :$administrationContext :$canViewRelations :$canViewSales title="Creditfacturen">
    <div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-2xl font-bold">Creditfacturen</h1><p class="mt-1 text-slate-600">Bekijk volledige credits op historische verkoopfacturen.</p></div>@if($canManageCreditDrafts)<a href="{{ route('sales.credit-invoices.create') }}" class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-blue-700">Nieuwe creditfactuur</a>@endif</div>
    <form method="GET" action="{{ route('sales.credit-invoices.index') }}" class="mt-6 grid gap-4 rounded-xl bg-white p-4 shadow-sm md:grid-cols-4">
        <label class="md:col-span-2">Zoeken<input name="q" value="{{ request('q') }}" class="mt-1 w-full rounded-lg border-slate-300" placeholder="Nummer of historische klantnaam"></label>
        <label>Status<select name="status" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Alle statussen</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $statusPresenter::label($status) }}</option>@endforeach</select></label>
        <label>Sortering<select name="sort" class="mt-1 w-full rounded-lg border-slate-300"><option value="credit_date" @selected(request('sort','credit_date')==='credit_date')>Creditdatum</option><option value="number" @selected(request('sort')==='number')>Creditnummer</option><option value="customer_name" @selected(request('sort')==='customer_name')>Klantnaam</option><option value="status" @selected(request('sort')==='status')>Status</option></select></label>
        <label>Vanaf<input type="date" name="date_from" value="{{ request('date_from') }}" class="mt-1 w-full rounded-lg border-slate-300"></label><label>Tot en met<input type="date" name="date_to" value="{{ request('date_to') }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
        <label>Richting<select name="direction" class="mt-1 w-full rounded-lg border-slate-300"><option value="desc" @selected(request('direction','desc')==='desc')>Aflopend</option><option value="asc" @selected(request('direction')==='asc')>Oplopend</option></select></label>
        <div class="flex items-end gap-3"><button class="rounded-lg bg-slate-900 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-slate-900">Filteren</button>@if($hasActiveFilters)<a href="{{ route('sales.credit-invoices.index') }}" class="px-3 py-3 font-semibold text-blue-700">Wissen</a>@endif</div>
    </form>
    @if($credits->total === 0)
        <section class="mt-6 rounded-xl bg-white p-8 text-center shadow-sm"><h2 class="text-lg font-bold">{{ $hasActiveFilters ? 'Geen creditfacturen gevonden.' : 'Nog geen creditfacturen.' }}</h2>@if(!$hasActiveFilters && $canManageCreditDrafts)<a href="{{ route('sales.credit-invoices.create') }}" class="mt-4 inline-block font-semibold text-blue-700">Nieuwe creditfactuur</a>@endif</section>
    @else
        <div class="mt-6 hidden overflow-x-auto rounded-xl bg-white shadow-sm md:block"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr>@foreach(['Creditnummer','Bronfactuur','Klant','Creditdatum','Status','Valuta','Totaal'] as $heading)<th scope="col" class="px-4 py-3">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y">@foreach($credits->items as $item)<tr><td class="px-4 py-3"><a class="font-semibold text-blue-700" href="{{ route('sales.credit-invoices.show',$item->id->toString()) }}">{{ $item->number->value() }}</a></td><td class="px-4 py-3">{{ $item->sourceInvoiceNumber->value() }}</td><td class="px-4 py-3">{{ $item->customerName->toString() }}</td><td class="px-4 py-3">{{ $item->creditDate->format('d-m-Y') }}</td><td class="px-4 py-3">{{ $statusPresenter::label($item->status) }}</td><td class="px-4 py-3">{{ $item->currency->code() }}</td><td class="px-4 py-3 font-semibold">{{ $moneyFormatter->format($item->total) }}</td></tr>@endforeach</tbody></table></div>
        <div class="mt-6 space-y-3 md:hidden">@foreach($credits->items as $item)<a href="{{ route('sales.credit-invoices.show',$item->id->toString()) }}" class="block rounded-xl bg-white p-4 shadow-sm focus:ring-2 focus:ring-blue-700"><span class="font-bold text-blue-700">{{ $item->number->value() }}</span><span class="float-right">{{ $statusPresenter::label($item->status) }}</span><p class="mt-2">{{ $item->customerName->toString() }}</p><p class="text-sm text-slate-600">Bron {{ $item->sourceInvoiceNumber->value() }} · {{ $item->creditDate->format('d-m-Y') }}</p><p class="mt-3 font-semibold">{{ $moneyFormatter->format($item->total) }}</p></a>@endforeach</div>
        @php($lastPage=max(1,(int)ceil($credits->total/$credits->perPage)))
        <nav class="mt-6 flex justify-between" aria-label="Paginering">@if($credits->page>1)<a class="font-semibold text-blue-700" href="{{ route('sales.credit-invoices.index',$queryParameters+['page'=>$credits->page-1]) }}">Vorige</a>@else<span></span>@endif<span>Pagina {{ $credits->page }} van {{ $lastPage }}</span>@if($credits->page<$lastPage)<a class="font-semibold text-blue-700" href="{{ route('sales.credit-invoices.index',$queryParameters+['page'=>$credits->page+1]) }}">Volgende</a>@endif</nav>
    @endif
</x-layouts.app>
