<x-layouts.app :$domainUser :$administrationContext :$canViewRelations :$canViewSales title="Creditfactuur {{ $detail->invoice->number()->value() }}">
    @php($credit=$detail->invoice)
    <div><p class="text-sm font-medium text-slate-500">Creditfactuur</p><h1 class="text-2xl font-bold">{{ $credit->number()->value() }}</h1><p class="mt-1">{{ $statusPresenter::label($credit->status()) }}</p></div>
    <div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Document</h2><dl class="mt-4 grid gap-3"><div><dt class="text-sm text-slate-500">Creditdatum</dt><dd>{{ $credit->creditInvoiceDate()->format('d-m-Y') }}</dd></div><div><dt class="text-sm text-slate-500">Valuta</dt><dd>{{ $credit->currency()->code() }}</dd></div><div><dt class="text-sm text-slate-500">Bronfactuur</dt><dd><a class="font-semibold text-blue-700 focus:ring-2 focus:ring-blue-700" href="{{ route('sales.invoices.show',$credit->sourceInvoiceId()->toString()) }}">{{ $detail->sourceInvoiceNumber->value() }}</a></dd></div></dl></section>
        <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Historische klant</h2><p class="mt-4 font-semibold">{{ $credit->customerSnapshot()?->displayName()->toString() }}</p><p>{{ $credit->customerSnapshot()?->customerNumber()->toString() }}</p>@if($credit->invoiceAddressSnapshot())<address class="mt-4 not-italic text-slate-700">{{ $credit->invoiceAddressSnapshot()->addressLine()->value() }}<br>@if($credit->invoiceAddressSnapshot()->addressLine2()){{ $credit->invoiceAddressSnapshot()->addressLine2()?->value() }}<br>@endif{{ $credit->invoiceAddressSnapshot()->postalCode()->value() }} {{ $credit->invoiceAddressSnapshot()->city()->value() }}<br>{{ $credit->invoiceAddressSnapshot()->countryCode()->value() }}</address>@endif</section></div>
    <section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Source-derived creditregels</h2><p class="mt-1 text-sm text-slate-600">Deze regels zijn volledig overgenomen uit de bronfactuur en kunnen niet worden gewijzigd.</p><div class="mt-4 hidden overflow-x-auto md:block"><table class="w-full text-left"><thead><tr><th scope="col" class="py-2">Omschrijving</th><th scope="col">Aantal</th><th scope="col">Prijs per eenheid</th><th scope="col">Regeltotaal</th></tr></thead><tbody class="divide-y">@foreach($credit->lines() as $line)<tr><td class="py-3">{{ $line->description()->value() }}</td><td>{{ $line->quantity()->value() }}</td><td>{{ $moneyFormatter->format($line->unitPrice()) }}</td><td>{{ $moneyFormatter->format($line->lineTotal()) }}</td></tr>@endforeach</tbody></table></div><div class="mt-4 space-y-3 md:hidden">@foreach($credit->lines() as $line)<article class="rounded-lg border p-4"><h3 class="font-semibold">{{ $line->description()->value() }}</h3><p class="mt-2 text-sm">{{ $line->quantity()->value() }} × {{ $moneyFormatter->format($line->unitPrice()) }}</p><p class="mt-2 font-semibold">{{ $moneyFormatter->format($line->lineTotal()) }}</p></article>@endforeach</div></section>
    <section class="mt-6 rounded-xl bg-slate-900 p-6 text-white"><h2 class="text-lg font-bold">Totaal</h2><p class="mt-3 text-2xl font-bold">{{ $moneyFormatter->format($credit->total()) }}</p></section>
    @if(($canIssueCredits && $credit->status() === \App\Domain\Sales\Enums\SalesCreditInvoiceStatus::Draft) || (($canManageCreditDrafts && $credit->status() === \App\Domain\Sales\Enums\SalesCreditInvoiceStatus::Draft) || ($canIssueCredits && $credit->status() === \App\Domain\Sales\Enums\SalesCreditInvoiceStatus::Finalized)))<section class="mt-6"><h2 class="text-lg font-bold">Acties</h2><div class="mt-3 flex flex-wrap gap-3">@if($canIssueCredits && $credit->status() === \App\Domain\Sales\Enums\SalesCreditInvoiceStatus::Draft)<form method="POST" action="{{ route('sales.credit-invoices.finalize',$credit->id()->toString()) }}">@csrf<button class="rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white focus:ring-2 focus:ring-blue-700">Creditfactuur definitief maken</button></form>@endif @if(($canManageCreditDrafts && $credit->status() === \App\Domain\Sales\Enums\SalesCreditInvoiceStatus::Draft) || ($canIssueCredits && $credit->status() === \App\Domain\Sales\Enums\SalesCreditInvoiceStatus::Finalized))<form method="POST" action="{{ route('sales.credit-invoices.cancel',$credit->id()->toString()) }}">@csrf<button class="rounded-lg border border-red-700 px-4 py-3 font-semibold text-red-700 focus:ring-2 focus:ring-red-700">Creditfactuur annuleren</button></form>@endif</div></section>@endif
</x-layouts.app>
