@php
$transaction=$detail?->transaction;
$selected=[];
if($transaction){foreach($transaction->payment()->allocations() as $allocation){$selected[$allocation->openItemId()->toString()]=$allocation;}}
$oldAllocations=old('allocations');
if(is_array($oldAllocations)){$selected=[];foreach($oldAllocations as $allocation){if(is_array($allocation)&&!empty($allocation['open_item_id'])){$selected[$allocation['open_item_id']]=$allocation;}}}
$type=old('payment_type',$transaction?->payment()->type()->value ?? 'customer_receipt');
$relationId=old('relation_id',$transaction?->payment()->relationId()->toString());
$amount=old('amount',$transaction?->amount()->absolute()->amount());
@endphp
@if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-red-800" role="alert"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="grid gap-4 rounded-xl bg-white p-6 shadow-sm md:grid-cols-2">
<label>Bankrekening<select required name="bank_account_id" class="mt-1 w-full rounded border-slate-300"><option value="">Kies een bankrekening</option>@foreach($masterData->bankAccounts as $bank)<option value="{{ $bank->id()->toString() }}" @selected(old('bank_account_id',$transaction?->bankAccountId()->toString())===$bank->id()->toString())>{{ $bank->label()->value() }} · {{ $bank->iban()->value() }}</option>@endforeach</select></label>
<label>Transactiedatum<input required type="date" name="transaction_date" value="{{ old('transaction_date',$transaction?->transactionDate()->value()->format('Y-m-d') ?? now()->format('Y-m-d')) }}" class="mt-1 w-full rounded border-slate-300"></label>
<label>Type<select data-payment-type required name="payment_type" class="mt-1 w-full rounded border-slate-300"><option value="customer_receipt" @selected($type==='customer_receipt')>Klantontvangst</option><option value="supplier_payment" @selected($type==='supplier_payment')>Leveranciersbetaling</option></select></label>
<label>Bedrag (positief)<input data-transaction-amount required type="number" min="0.01" step="0.01" name="amount" value="{{ $amount }}" class="mt-1 w-full rounded border-slate-300"></label>
<label>Relatie<select data-payment-relation required name="relation_id" class="mt-1 w-full rounded border-slate-300"><option value="">Kies een relatie</option>@foreach($masterData->relations as $relation)<option value="{{ $relation->id()->toString() }}" @selected($relationId===$relation->id()->toString())>{{ $relation->code()->toString() }} · {{ $relation->displayName()->toString() }}</option>@endforeach</select></label>
<label>Referentie<input required maxlength="255" name="reference" value="{{ old('reference',$transaction?->reference()->value()) }}" class="mt-1 w-full rounded border-slate-300"></label>
<label class="md:col-span-2">Omschrijving<textarea required maxlength="1000" name="description" class="mt-1 w-full rounded border-slate-300">{{ old('description',$transaction?->description()->value()) }}</textarea></label>
</section>
<section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-bold">Openstaande posten en allocaties</h2><p id="allocation-help" class="mt-1 text-sm text-slate-600">Selecteer een openstaande post en vul daarna het allocatiebedrag in. Gedeeltelijke betaling per post is toegestaan.</p><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th>Selecteer</th><th>Bron / datum</th><th>Type</th><th>Oorspronkelijk</th><th>Openstaand</th><th>Vervaldatum</th><th>Allocatie</th></tr></thead><tbody>@foreach($masterData->openItems as $index=>$item)@php $allocation=$selected[$item->id()->toString()]??null; $isSelected=$allocation!==null; $allocationId=is_array($allocation)?($allocation['allocation_id']??''):$allocation?->id()->toString(); $allocationAmount=is_array($allocation)?($allocation['amount']??''):$allocation?->amount()->amount(); $itemType=$item->type()->value==='receivable'?'customer_receipt':'supplier_payment'; @endphp<tr data-open-item data-type="{{ $itemType }}" data-relation="{{ $item->relationId()->toString() }}" class="border-t"><td class="py-3"><label class="inline-flex items-center gap-2"><input id="allocation-checkbox-{{ $index }}" data-allocation-checkbox type="checkbox" name="allocations[{{ $index }}][open_item_id]" value="{{ $item->id()->toString() }}" aria-controls="allocation-amount-{{ $index }}" @checked($isSelected)><span class="sr-only">Selecteer openstaande post {{ $item->journalEntryId()->toString() }}</span></label></td><td class="py-3"><span class="font-mono text-xs">{{ $item->journalEntryId()->toString() }}</span><br>{{ $item->openedOn()->value()->format('d-m-Y') }}</td><td>{{ $item->type()->value==='receivable'?'Debiteur':'Crediteur' }}</td><td>{{ $moneyFormatter->format($item->originalAmount()) }}</td><td>{{ $moneyFormatter->format($item->openAmount()) }}</td><td>{{ $item->dueDate()?->format('d-m-Y') ?? '—' }}</td><td><input type="hidden" name="allocations[{{ $index }}][allocation_id]" value="{{ $allocationId }}"><label for="allocation-amount-{{ $index }}" class="sr-only">Allocatiebedrag voor openstaande post {{ $item->journalEntryId()->toString() }}</label><input id="allocation-amount-{{ $index }}" data-allocation-amount type="number" min="0.01" step="0.01" name="allocations[{{ $index }}][amount]" value="{{ $allocationAmount }}" aria-describedby="allocation-help allocation-required-{{ $index }}" @disabled(!$isSelected) @required($isSelected) class="w-32 rounded border-slate-300 disabled:cursor-not-allowed disabled:bg-slate-100"><span id="allocation-required-{{ $index }}" data-allocation-required class="ml-2 hidden text-xs font-medium text-red-700">Bedrag vereist</span></td></tr>@endforeach</tbody></table></div><dl class="mt-4 grid max-w-md grid-cols-2 gap-2"><dt>Transactiebedrag</dt><dd data-total-transaction>{{ $amount ?: '0' }}</dd><dt>Totaal toegewezen</dt><dd data-total-allocated>0,00</dd><dt>Nog toe te wijzen</dt><dd data-total-remaining>0,00</dd></dl></section>
<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.querySelector('[data-payment-type]'),relation=document.querySelector('[data-payment-relation]'),amount=document.querySelector('[data-transaction-amount]'),rows=Array.from(document.querySelectorAll('[data-open-item]'));const update=()=>{let total=0;rows.forEach(row=>{const visible=row.dataset.type===type.value&&row.dataset.relation===relation.value;row.hidden=!visible;const checkbox=row.querySelector('[data-allocation-checkbox]'),allocation=row.querySelector('[data-allocation-amount]'),required=row.querySelector('[data-allocation-required]');if(!visible)checkbox.checked=false;allocation.disabled=!checkbox.checked;allocation.required=checkbox.checked;allocation.setAttribute('aria-required',checkbox.checked?'true':'false');const incomplete=checkbox.checked&&allocation.value==='';required.classList.toggle('hidden',!incomplete);row.classList.toggle('bg-blue-50',checkbox.checked);if(checkbox.checked&&allocation.value!=='')total+=Number(allocation.value)});const transaction=Number(amount.value||0);document.querySelector('[data-total-transaction]').textContent=transaction.toFixed(2);document.querySelector('[data-total-allocated]').textContent=total.toFixed(2);document.querySelector('[data-total-remaining]').textContent=(transaction-total).toFixed(2)};document.querySelector('form').addEventListener('input',event=>{update();if(event.target.matches('[data-allocation-checkbox]')&&event.target.checked){event.target.closest('[data-open-item]').querySelector('[data-allocation-amount]').focus()}});update()});</script>
