@php $transaction=$detail->transaction; @endphp
<x-layouts.app title="Bankbetaling terugdraaien" :$domainUser :$administrationContext>
<div class="max-w-3xl"><h1 class="text-2xl font-bold">Bankbetaling terugdraaien</h1><p class="mt-2 text-slate-600">Controleer de gegevens zorgvuldig. De oorspronkelijke betaling blijft historisch bestaan; deze handeling maakt een contra-boeking en draait de gekoppelde settlements terug.</p>
<section class="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 class="font-bold">Oorspronkelijke betaling</h2><dl class="mt-4 grid grid-cols-2 gap-3"><dt>Referentie</dt><dd>{{ $transaction->reference()->value() }}</dd><dt>Relatie</dt><dd>{{ $detail->relation->displayName()->toString() }}</dd><dt>Type</dt><dd>{{ $transaction->payment()->type()->value==='customer_receipt'?'Klantontvangst':'Leveranciersbetaling' }}</dd><dt>Bedrag</dt><dd>{{ $moneyFormatter->format($transaction->amount()) }}</dd><dt>Boekingsdatum</dt><dd>{{ $detail->reversal->originalPostingDate?->value()->format('d-m-Y') }}</dd><dt>Originele JournalEntry</dt><dd class="font-mono text-xs">{{ $detail->reversal->originalJournalEntryId?->toString() }}</dd><dt>Allocaties</dt><dd>{{ $detail->reversal->allocationCount }}</dd><dt>Settlements</dt><dd>{{ $detail->reversal->settlementCount }}</dd></dl></section>
<form method="POST" action="{{ route('banking.payments.reverse.store',$transaction->id()->toString()) }}" class="mt-6 space-y-5 rounded-xl border border-red-200 bg-white p-6 shadow-sm">@csrf
<label class="block font-semibold">Terugdraaiboekingsdatum<input required type="date" name="reversal_posting_date" value="{{ old('reversal_posting_date',now()->format('Y-m-d')) }}" class="mt-1 block w-full rounded border-slate-300"></label>
<label class="block font-semibold">Reden<textarea required maxlength="500" name="reason" rows="4" class="mt-1 block w-full rounded border-slate-300">{{ old('reason') }}</textarea></label>
@if($errors->any())<div class="rounded bg-red-50 p-3 text-red-800">Controleer de ingevulde gegevens.</div>@endif
<div class="flex gap-3"><button class="rounded bg-red-700 px-4 py-3 font-semibold text-white">Betaling definitief terugdraaien</button><a class="rounded border px-4 py-3" href="{{ route('banking.payments.show',$transaction->id()->toString()) }}">Annuleren</a></div></form></div>
</x-layouts.app>
