@php $transaction=$detail->transaction; $posting=$detail->posting; $payment=$transaction->paymentOrNull(); @endphp
<x-layouts.app title="Banktransactie {{ $transaction->reference()->value() }}" :$domainUser :$administrationContext>
<div class="flex justify-between"><div><h1 class="text-2xl font-bold">Banktransactie {{ $transaction->reference()->value() }}</h1><p>{{ $payment ? ($payment->type()->value==='customer_receipt'?'Klantontvangst':'Leveranciersbetaling') : 'Overig' }}</p></div><div>@if($payment&&$transaction->status()->value==='draft'&&$canManage)<a href="{{ route('banking.payments.edit',$transaction->id()->toString()) }}">Bewerken</a><form method="POST" action="{{ route('banking.payments.cancel',$transaction->id()->toString()) }}">@csrf<button>Annuleren</button></form><form method="POST" action="{{ route('banking.payments.finalize',$transaction->id()->toString()) }}">@csrf<button>Finaliseren</button></form>@endif @if($canReverse&&$detail->reversal->status===\App\Application\Banking\BankTransactionReversalEligibilityStatus::Eligible)<a href="{{ route('banking.payments.reverse.create',$transaction->id()->toString()) }}">{{ $payment ? 'Betaling terugdraaien' : 'Transactie terugdraaien' }}</a>@endif</div></div>
@if($payment&&$transaction->status()->value==='finalized'&&$canPost)<form method="POST" action="{{ route('banking.payments.post',$transaction->id()->toString()) }}">@csrf<input required type="date" name="posting_date" value="{{ old('posting_date',now()->format('Y-m-d')) }}"><button>Boeken</button></form>@endif
<section class="mt-6 rounded-xl bg-white p-6"><dl class="grid grid-cols-2 gap-3"><dt>Type</dt><dd>{{ $payment ? ($payment->type()->value==='customer_receipt'?'Klantontvangst':'Leveranciersbetaling') : 'Overig' }}</dd>@if($payment)<dt>Relatie</dt><dd>{{ $detail->relation?->displayName()->toString() }}</dd>@else<dt>Tegenrekening</dt><dd>{{ $detail->contraAccount?->code()->toString() }} {{ $detail->contraAccount?->name()->toString() }}</dd>@endif<dt>Bedrag</dt><dd>{{ $moneyFormatter->format($transaction->amount()) }}</dd><dt>Omschrijving</dt><dd>{{ $transaction->description()->value() }}</dd>@if($posting)<dt>Boekingsdatum</dt><dd>{{ $posting->posting->postingDate->value()->format('d-m-Y') }}</dd><dt>JournalEntry</dt><dd>{{ $posting->posting->journalEntryId->toString() }}</dd>@endif</dl></section>
@if($payment)<section class="mt-6 rounded-xl bg-white p-6"><h2>Allocaties</h2><ul>@foreach($payment->allocations() as $index=>$allocation)@php $item=$detail->openItems[$allocation->openItemId()->toString()]; $result=$posting?->settlements[$index]??null; @endphp<li>{{ $item->journalEntryId()->toString() }} · {{ $moneyFormatter->format($item->originalAmount()) }} · {{ $moneyFormatter->format($allocation->amount()) }} · {{ $result ? $moneyFormatter->format($result->settlementAmount) : '—' }} · {{ $moneyFormatter->format($result?->remainingOpenAmount ?? $item->openAmount()) }}</li>@endforeach</ul></section>@endif
@if($detail->reversal->reversal)@php $reversal=$detail->reversal->reversal; @endphp<section class="mt-6 rounded-xl bg-white p-6"><h2>Teruggedraaid</h2><p>{{ $reversal->reason->value() }}</p><dl><dt>Contra-boeking</dt><dd>{{ $reversal->reversalJournalEntryId->toString() }}</dd><dt>Originele settlements</dt><dd>{{ $detail->reversal->settlementCount }}</dd><dt>Teruggedraaide settlements</dt><dd>{{ $detail->reversal->reversedSettlementCount }}</dd></dl>@foreach($detail->openItems as $item)<p>{{ $moneyFormatter->format($item->openAmount()) }}</p>@endforeach</section>@endif
@if(session('error')&&$canUpdateSettings)<p><a href="{{ route('settings.administration.edit') }}">Naar Beheer → Instellingen</a></p>@endif
</x-layouts.app>
